//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: BoundedArrayPrimitivesNested_Dcps.h
//  Source: test_msgs\msg\dds_opensplice\BoundedArrayPrimitivesNested_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _BOUNDEDARRAYPRIMITIVESNESTED_DCPS_H_
#define _BOUNDEDARRAYPRIMITIVESNESTED_DCPS_H_

#include "sacpp_mapping.h"
#include "BoundedArrayPrimitivesNested_.h"
#include "dds_dcps.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace msg
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs BoundedArrayPrimitivesNested_TypeSupportInterface;

         typedef BoundedArrayPrimitivesNested_TypeSupportInterface * BoundedArrayPrimitivesNested_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < BoundedArrayPrimitivesNested_TypeSupportInterface> BoundedArrayPrimitivesNested_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < BoundedArrayPrimitivesNested_TypeSupportInterface> BoundedArrayPrimitivesNested_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs BoundedArrayPrimitivesNested_DataWriter;

         typedef BoundedArrayPrimitivesNested_DataWriter * BoundedArrayPrimitivesNested_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < BoundedArrayPrimitivesNested_DataWriter> BoundedArrayPrimitivesNested_DataWriter_var;
         typedef DDS_DCPSInterface_out < BoundedArrayPrimitivesNested_DataWriter> BoundedArrayPrimitivesNested_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs BoundedArrayPrimitivesNested_DataReader;

         typedef BoundedArrayPrimitivesNested_DataReader * BoundedArrayPrimitivesNested_DataReader_ptr;
         typedef DDS_DCPSInterface_var < BoundedArrayPrimitivesNested_DataReader> BoundedArrayPrimitivesNested_DataReader_var;
         typedef DDS_DCPSInterface_out < BoundedArrayPrimitivesNested_DataReader> BoundedArrayPrimitivesNested_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs BoundedArrayPrimitivesNested_DataReaderView;

         typedef BoundedArrayPrimitivesNested_DataReaderView * BoundedArrayPrimitivesNested_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < BoundedArrayPrimitivesNested_DataReaderView> BoundedArrayPrimitivesNested_DataReaderView_var;
         typedef DDS_DCPSInterface_out < BoundedArrayPrimitivesNested_DataReaderView> BoundedArrayPrimitivesNested_DataReaderView_out;

         struct BoundedArrayPrimitivesNested_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < BoundedArrayPrimitivesNested_, struct BoundedArrayPrimitivesNested_Seq_uniq_> BoundedArrayPrimitivesNested_Seq;
         typedef DDS_DCPSSequence_var < BoundedArrayPrimitivesNested_Seq> BoundedArrayPrimitivesNested_Seq_var;
         typedef DDS_DCPSSequence_out < BoundedArrayPrimitivesNested_Seq> BoundedArrayPrimitivesNested_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs BoundedArrayPrimitivesNested_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef BoundedArrayPrimitivesNested_TypeSupportInterface_ptr _ptr_type;
            typedef BoundedArrayPrimitivesNested_TypeSupportInterface_var _var_type;

            static BoundedArrayPrimitivesNested_TypeSupportInterface_ptr _duplicate (BoundedArrayPrimitivesNested_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static BoundedArrayPrimitivesNested_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static BoundedArrayPrimitivesNested_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static BoundedArrayPrimitivesNested_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            BoundedArrayPrimitivesNested_TypeSupportInterface_ptr _this () { return this; }


         protected:
            BoundedArrayPrimitivesNested_TypeSupportInterface () {};
            ~BoundedArrayPrimitivesNested_TypeSupportInterface () {};
         private:
            BoundedArrayPrimitivesNested_TypeSupportInterface (const BoundedArrayPrimitivesNested_TypeSupportInterface &);
            BoundedArrayPrimitivesNested_TypeSupportInterface & operator = (const BoundedArrayPrimitivesNested_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs BoundedArrayPrimitivesNested_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef BoundedArrayPrimitivesNested_DataWriter_ptr _ptr_type;
            typedef BoundedArrayPrimitivesNested_DataWriter_var _var_type;

            static BoundedArrayPrimitivesNested_DataWriter_ptr _duplicate (BoundedArrayPrimitivesNested_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static BoundedArrayPrimitivesNested_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static BoundedArrayPrimitivesNested_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static BoundedArrayPrimitivesNested_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            BoundedArrayPrimitivesNested_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const BoundedArrayPrimitivesNested_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const BoundedArrayPrimitivesNested_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const BoundedArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const BoundedArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const BoundedArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const BoundedArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const BoundedArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const BoundedArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const BoundedArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const BoundedArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (BoundedArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const BoundedArrayPrimitivesNested_& instance_data) = 0;

         protected:
            BoundedArrayPrimitivesNested_DataWriter () {};
            ~BoundedArrayPrimitivesNested_DataWriter () {};
         private:
            BoundedArrayPrimitivesNested_DataWriter (const BoundedArrayPrimitivesNested_DataWriter &);
            BoundedArrayPrimitivesNested_DataWriter & operator = (const BoundedArrayPrimitivesNested_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs BoundedArrayPrimitivesNested_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef BoundedArrayPrimitivesNested_DataReader_ptr _ptr_type;
            typedef BoundedArrayPrimitivesNested_DataReader_var _var_type;

            static BoundedArrayPrimitivesNested_DataReader_ptr _duplicate (BoundedArrayPrimitivesNested_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static BoundedArrayPrimitivesNested_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static BoundedArrayPrimitivesNested_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static BoundedArrayPrimitivesNested_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            BoundedArrayPrimitivesNested_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (BoundedArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (BoundedArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (BoundedArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const BoundedArrayPrimitivesNested_& instance) = 0;

         protected:
            BoundedArrayPrimitivesNested_DataReader () {};
            ~BoundedArrayPrimitivesNested_DataReader () {};
         private:
            BoundedArrayPrimitivesNested_DataReader (const BoundedArrayPrimitivesNested_DataReader &);
            BoundedArrayPrimitivesNested_DataReader & operator = (const BoundedArrayPrimitivesNested_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs BoundedArrayPrimitivesNested_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef BoundedArrayPrimitivesNested_DataReaderView_ptr _ptr_type;
            typedef BoundedArrayPrimitivesNested_DataReaderView_var _var_type;

            static BoundedArrayPrimitivesNested_DataReaderView_ptr _duplicate (BoundedArrayPrimitivesNested_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static BoundedArrayPrimitivesNested_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static BoundedArrayPrimitivesNested_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static BoundedArrayPrimitivesNested_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            BoundedArrayPrimitivesNested_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (BoundedArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (BoundedArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (BoundedArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (BoundedArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const BoundedArrayPrimitivesNested_& instance) = 0;

         protected:
            BoundedArrayPrimitivesNested_DataReaderView () {};
            ~BoundedArrayPrimitivesNested_DataReaderView () {};
         private:
            BoundedArrayPrimitivesNested_DataReaderView (const BoundedArrayPrimitivesNested_DataReaderView &);
            BoundedArrayPrimitivesNested_DataReaderView & operator = (const BoundedArrayPrimitivesNested_DataReaderView &);
         };

      }
   }
}




#endif
