//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: DynamicArrayStaticArrayPrimitivesNested_Dcps.h
//  Source: test_msgs\msg\dds_opensplice\DynamicArrayStaticArrayPrimitivesNested_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _DYNAMICARRAYSTATICARRAYPRIMITIVESNESTED_DCPS_H_
#define _DYNAMICARRAYSTATICARRAYPRIMITIVESNESTED_DCPS_H_

#include "sacpp_mapping.h"
#include "DynamicArrayStaticArrayPrimitivesNested_.h"
#include "dds_dcps.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace msg
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface;

         typedef DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface * DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface> DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface> DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayStaticArrayPrimitivesNested_DataWriter;

         typedef DynamicArrayStaticArrayPrimitivesNested_DataWriter * DynamicArrayStaticArrayPrimitivesNested_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < DynamicArrayStaticArrayPrimitivesNested_DataWriter> DynamicArrayStaticArrayPrimitivesNested_DataWriter_var;
         typedef DDS_DCPSInterface_out < DynamicArrayStaticArrayPrimitivesNested_DataWriter> DynamicArrayStaticArrayPrimitivesNested_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayStaticArrayPrimitivesNested_DataReader;

         typedef DynamicArrayStaticArrayPrimitivesNested_DataReader * DynamicArrayStaticArrayPrimitivesNested_DataReader_ptr;
         typedef DDS_DCPSInterface_var < DynamicArrayStaticArrayPrimitivesNested_DataReader> DynamicArrayStaticArrayPrimitivesNested_DataReader_var;
         typedef DDS_DCPSInterface_out < DynamicArrayStaticArrayPrimitivesNested_DataReader> DynamicArrayStaticArrayPrimitivesNested_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayStaticArrayPrimitivesNested_DataReaderView;

         typedef DynamicArrayStaticArrayPrimitivesNested_DataReaderView * DynamicArrayStaticArrayPrimitivesNested_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < DynamicArrayStaticArrayPrimitivesNested_DataReaderView> DynamicArrayStaticArrayPrimitivesNested_DataReaderView_var;
         typedef DDS_DCPSInterface_out < DynamicArrayStaticArrayPrimitivesNested_DataReaderView> DynamicArrayStaticArrayPrimitivesNested_DataReaderView_out;

         struct DynamicArrayStaticArrayPrimitivesNested_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < DynamicArrayStaticArrayPrimitivesNested_, struct DynamicArrayStaticArrayPrimitivesNested_Seq_uniq_> DynamicArrayStaticArrayPrimitivesNested_Seq;
         typedef DDS_DCPSSequence_var < DynamicArrayStaticArrayPrimitivesNested_Seq> DynamicArrayStaticArrayPrimitivesNested_Seq_var;
         typedef DDS_DCPSSequence_out < DynamicArrayStaticArrayPrimitivesNested_Seq> DynamicArrayStaticArrayPrimitivesNested_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_ptr _ptr_type;
            typedef DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_var _var_type;

            static DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_ptr _duplicate (DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface_ptr _this () { return this; }


         protected:
            DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface () {};
            ~DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface () {};
         private:
            DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface (const DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface &);
            DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface & operator = (const DynamicArrayStaticArrayPrimitivesNested_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayStaticArrayPrimitivesNested_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef DynamicArrayStaticArrayPrimitivesNested_DataWriter_ptr _ptr_type;
            typedef DynamicArrayStaticArrayPrimitivesNested_DataWriter_var _var_type;

            static DynamicArrayStaticArrayPrimitivesNested_DataWriter_ptr _duplicate (DynamicArrayStaticArrayPrimitivesNested_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static DynamicArrayStaticArrayPrimitivesNested_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static DynamicArrayStaticArrayPrimitivesNested_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static DynamicArrayStaticArrayPrimitivesNested_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            DynamicArrayStaticArrayPrimitivesNested_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const DynamicArrayStaticArrayPrimitivesNested_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const DynamicArrayStaticArrayPrimitivesNested_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const DynamicArrayStaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const DynamicArrayStaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const DynamicArrayStaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const DynamicArrayStaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const DynamicArrayStaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const DynamicArrayStaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const DynamicArrayStaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const DynamicArrayStaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (DynamicArrayStaticArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const DynamicArrayStaticArrayPrimitivesNested_& instance_data) = 0;

         protected:
            DynamicArrayStaticArrayPrimitivesNested_DataWriter () {};
            ~DynamicArrayStaticArrayPrimitivesNested_DataWriter () {};
         private:
            DynamicArrayStaticArrayPrimitivesNested_DataWriter (const DynamicArrayStaticArrayPrimitivesNested_DataWriter &);
            DynamicArrayStaticArrayPrimitivesNested_DataWriter & operator = (const DynamicArrayStaticArrayPrimitivesNested_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayStaticArrayPrimitivesNested_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef DynamicArrayStaticArrayPrimitivesNested_DataReader_ptr _ptr_type;
            typedef DynamicArrayStaticArrayPrimitivesNested_DataReader_var _var_type;

            static DynamicArrayStaticArrayPrimitivesNested_DataReader_ptr _duplicate (DynamicArrayStaticArrayPrimitivesNested_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static DynamicArrayStaticArrayPrimitivesNested_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static DynamicArrayStaticArrayPrimitivesNested_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static DynamicArrayStaticArrayPrimitivesNested_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            DynamicArrayStaticArrayPrimitivesNested_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (DynamicArrayStaticArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (DynamicArrayStaticArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (DynamicArrayStaticArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const DynamicArrayStaticArrayPrimitivesNested_& instance) = 0;

         protected:
            DynamicArrayStaticArrayPrimitivesNested_DataReader () {};
            ~DynamicArrayStaticArrayPrimitivesNested_DataReader () {};
         private:
            DynamicArrayStaticArrayPrimitivesNested_DataReader (const DynamicArrayStaticArrayPrimitivesNested_DataReader &);
            DynamicArrayStaticArrayPrimitivesNested_DataReader & operator = (const DynamicArrayStaticArrayPrimitivesNested_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayStaticArrayPrimitivesNested_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef DynamicArrayStaticArrayPrimitivesNested_DataReaderView_ptr _ptr_type;
            typedef DynamicArrayStaticArrayPrimitivesNested_DataReaderView_var _var_type;

            static DynamicArrayStaticArrayPrimitivesNested_DataReaderView_ptr _duplicate (DynamicArrayStaticArrayPrimitivesNested_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static DynamicArrayStaticArrayPrimitivesNested_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static DynamicArrayStaticArrayPrimitivesNested_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static DynamicArrayStaticArrayPrimitivesNested_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            DynamicArrayStaticArrayPrimitivesNested_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (DynamicArrayStaticArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (DynamicArrayStaticArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (DynamicArrayStaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (DynamicArrayStaticArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const DynamicArrayStaticArrayPrimitivesNested_& instance) = 0;

         protected:
            DynamicArrayStaticArrayPrimitivesNested_DataReaderView () {};
            ~DynamicArrayStaticArrayPrimitivesNested_DataReaderView () {};
         private:
            DynamicArrayStaticArrayPrimitivesNested_DataReaderView (const DynamicArrayStaticArrayPrimitivesNested_DataReaderView &);
            DynamicArrayStaticArrayPrimitivesNested_DataReaderView & operator = (const DynamicArrayStaticArrayPrimitivesNested_DataReaderView &);
         };

      }
   }
}




#endif
