//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: DynamicArrayStaticArrayPrimitivesNested_.h
//  Source: test_msgs\msg\dds_opensplice\DynamicArrayStaticArrayPrimitivesNested_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _DYNAMICARRAYSTATICARRAYPRIMITIVESNESTED__H_
#define _DYNAMICARRAYSTATICARRAYPRIMITIVESNESTED__H_

#include "sacpp_mapping.h"
#include "StaticArrayPrimitives_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct DynamicArrayStaticArrayPrimitivesNested_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayStaticArrayPrimitivesNested_
         {
               struct _dynamic_array_static_array_primitive_values__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < StaticArrayPrimitives_, struct _dynamic_array_static_array_primitive_values__seq_uniq_> _dynamic_array_static_array_primitive_values__seq;
               typedef DDS_DCPSSequence_var < _dynamic_array_static_array_primitive_values__seq> _dynamic_array_static_array_primitive_values__seq_var;
               typedef DDS_DCPSSequence_out < _dynamic_array_static_array_primitive_values__seq> _dynamic_array_static_array_primitive_values__seq_out;
               _dynamic_array_static_array_primitive_values__seq dynamic_array_static_array_primitive_values_;
         };

         typedef DDS_DCPSStruct_var < DynamicArrayStaticArrayPrimitivesNested_> DynamicArrayStaticArrayPrimitivesNested__var;
         typedef DDS_DCPSStruct_out < DynamicArrayStaticArrayPrimitivesNested_> DynamicArrayStaticArrayPrimitivesNested__out;
      }
   }
}




#endif
