//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: StaticArrayPrimitivesNested_.h
//  Source: test_msgs\msg\dds_opensplice\StaticArrayPrimitivesNested_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _STATICARRAYPRIMITIVESNESTED__H_
#define _STATICARRAYPRIMITIVESNESTED__H_

#include "sacpp_mapping.h"
#include "StaticArrayPrimitives_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct StaticArrayPrimitivesNested_;
         typedef test_msgs::msg::dds_::StaticArrayPrimitives_ test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice;
         typedef test_msgs::msg::dds_::StaticArrayPrimitives_ test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4[4];
         ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs extern test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice * test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_alloc ();
         ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs extern void test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_free (test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice *);
         ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs extern void test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_copy (test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice* to, const test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice* from);
         ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs extern test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice *test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_dup (const test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice* from);

         struct test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_uniq_ {};
         typedef DDS_DCPS_VArray_var< test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4, test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice, struct test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_uniq_> test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_var;
         typedef DDS_DCPS_Array_forany< test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4, test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice, struct test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_uniq_> test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_forany;
         typedef DDS_DCPS_VLArray_out< test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4, test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice, test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_var, test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_uniq_> test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_out;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitivesNested_
         {
               test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4 static_array_primitive_values_;
         };

         typedef DDS_DCPSStruct_var < StaticArrayPrimitivesNested_> StaticArrayPrimitivesNested__var;
         typedef DDS_DCPSStruct_out < StaticArrayPrimitivesNested_> StaticArrayPrimitivesNested__out;
      }
   }
}
template <>
test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice* DDS_DCPS_ArrayHelper < test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4, test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice, test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4, test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice, test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_uniq_>::copy (test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice *to, const test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice* from);
template <>
void DDS_DCPS_ArrayHelper < test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4, test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice, test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_uniq_>::free (test_msgs::msg::dds_::test_msgs__StaticArrayPrimitivesNested__test_msgs__msg__dds___StaticArrayPrimitives__array_4_slice *ptr);




#endif
