//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: StaticArrayPrimitivesNested_Dcps.h
//  Source: test_msgs\msg\dds_opensplice\StaticArrayPrimitivesNested_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _STATICARRAYPRIMITIVESNESTED_DCPS_H_
#define _STATICARRAYPRIMITIVESNESTED_DCPS_H_

#include "sacpp_mapping.h"
#include "StaticArrayPrimitivesNested_.h"
#include "dds_dcps.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace msg
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitivesNested_TypeSupportInterface;

         typedef StaticArrayPrimitivesNested_TypeSupportInterface * StaticArrayPrimitivesNested_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < StaticArrayPrimitivesNested_TypeSupportInterface> StaticArrayPrimitivesNested_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < StaticArrayPrimitivesNested_TypeSupportInterface> StaticArrayPrimitivesNested_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitivesNested_DataWriter;

         typedef StaticArrayPrimitivesNested_DataWriter * StaticArrayPrimitivesNested_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < StaticArrayPrimitivesNested_DataWriter> StaticArrayPrimitivesNested_DataWriter_var;
         typedef DDS_DCPSInterface_out < StaticArrayPrimitivesNested_DataWriter> StaticArrayPrimitivesNested_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitivesNested_DataReader;

         typedef StaticArrayPrimitivesNested_DataReader * StaticArrayPrimitivesNested_DataReader_ptr;
         typedef DDS_DCPSInterface_var < StaticArrayPrimitivesNested_DataReader> StaticArrayPrimitivesNested_DataReader_var;
         typedef DDS_DCPSInterface_out < StaticArrayPrimitivesNested_DataReader> StaticArrayPrimitivesNested_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitivesNested_DataReaderView;

         typedef StaticArrayPrimitivesNested_DataReaderView * StaticArrayPrimitivesNested_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < StaticArrayPrimitivesNested_DataReaderView> StaticArrayPrimitivesNested_DataReaderView_var;
         typedef DDS_DCPSInterface_out < StaticArrayPrimitivesNested_DataReaderView> StaticArrayPrimitivesNested_DataReaderView_out;

         struct StaticArrayPrimitivesNested_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < StaticArrayPrimitivesNested_, struct StaticArrayPrimitivesNested_Seq_uniq_> StaticArrayPrimitivesNested_Seq;
         typedef DDS_DCPSSequence_var < StaticArrayPrimitivesNested_Seq> StaticArrayPrimitivesNested_Seq_var;
         typedef DDS_DCPSSequence_out < StaticArrayPrimitivesNested_Seq> StaticArrayPrimitivesNested_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitivesNested_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef StaticArrayPrimitivesNested_TypeSupportInterface_ptr _ptr_type;
            typedef StaticArrayPrimitivesNested_TypeSupportInterface_var _var_type;

            static StaticArrayPrimitivesNested_TypeSupportInterface_ptr _duplicate (StaticArrayPrimitivesNested_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static StaticArrayPrimitivesNested_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitivesNested_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitivesNested_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            StaticArrayPrimitivesNested_TypeSupportInterface_ptr _this () { return this; }


         protected:
            StaticArrayPrimitivesNested_TypeSupportInterface () {};
            ~StaticArrayPrimitivesNested_TypeSupportInterface () {};
         private:
            StaticArrayPrimitivesNested_TypeSupportInterface (const StaticArrayPrimitivesNested_TypeSupportInterface &);
            StaticArrayPrimitivesNested_TypeSupportInterface & operator = (const StaticArrayPrimitivesNested_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitivesNested_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef StaticArrayPrimitivesNested_DataWriter_ptr _ptr_type;
            typedef StaticArrayPrimitivesNested_DataWriter_var _var_type;

            static StaticArrayPrimitivesNested_DataWriter_ptr _duplicate (StaticArrayPrimitivesNested_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static StaticArrayPrimitivesNested_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitivesNested_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitivesNested_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            StaticArrayPrimitivesNested_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const StaticArrayPrimitivesNested_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const StaticArrayPrimitivesNested_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const StaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const StaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const StaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const StaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const StaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const StaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const StaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const StaticArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (StaticArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const StaticArrayPrimitivesNested_& instance_data) = 0;

         protected:
            StaticArrayPrimitivesNested_DataWriter () {};
            ~StaticArrayPrimitivesNested_DataWriter () {};
         private:
            StaticArrayPrimitivesNested_DataWriter (const StaticArrayPrimitivesNested_DataWriter &);
            StaticArrayPrimitivesNested_DataWriter & operator = (const StaticArrayPrimitivesNested_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitivesNested_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef StaticArrayPrimitivesNested_DataReader_ptr _ptr_type;
            typedef StaticArrayPrimitivesNested_DataReader_var _var_type;

            static StaticArrayPrimitivesNested_DataReader_ptr _duplicate (StaticArrayPrimitivesNested_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static StaticArrayPrimitivesNested_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitivesNested_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitivesNested_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            StaticArrayPrimitivesNested_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (StaticArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (StaticArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (StaticArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const StaticArrayPrimitivesNested_& instance) = 0;

         protected:
            StaticArrayPrimitivesNested_DataReader () {};
            ~StaticArrayPrimitivesNested_DataReader () {};
         private:
            StaticArrayPrimitivesNested_DataReader (const StaticArrayPrimitivesNested_DataReader &);
            StaticArrayPrimitivesNested_DataReader & operator = (const StaticArrayPrimitivesNested_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitivesNested_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef StaticArrayPrimitivesNested_DataReaderView_ptr _ptr_type;
            typedef StaticArrayPrimitivesNested_DataReaderView_var _var_type;

            static StaticArrayPrimitivesNested_DataReaderView_ptr _duplicate (StaticArrayPrimitivesNested_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static StaticArrayPrimitivesNested_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitivesNested_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitivesNested_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            StaticArrayPrimitivesNested_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (StaticArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (StaticArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (StaticArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (StaticArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const StaticArrayPrimitivesNested_& instance) = 0;

         protected:
            StaticArrayPrimitivesNested_DataReaderView () {};
            ~StaticArrayPrimitivesNested_DataReaderView () {};
         private:
            StaticArrayPrimitivesNested_DataReaderView (const StaticArrayPrimitivesNested_DataReaderView &);
            StaticArrayPrimitivesNested_DataReaderView & operator = (const StaticArrayPrimitivesNested_DataReaderView &);
         };

      }
   }
}




#endif
