//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Fibonacci_Feedback_.h
//  Source: test_msgs\action\dds_opensplice\Fibonacci_Feedback_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _FIBONACCI_FEEDBACK__H_
#define _FIBONACCI_FEEDBACK__H_

#include "sacpp_mapping.h"
#include "UUID_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace action
   {
      namespace dds_
      {
         struct Fibonacci_Feedback_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs Fibonacci_Feedback_
         {
               struct _sequence__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::Long, struct _sequence__seq_uniq_> _sequence__seq;
               typedef DDS_DCPSSequence_var < _sequence__seq> _sequence__seq_var;
               typedef DDS_DCPSSequence_out < _sequence__seq> _sequence__seq_out;
               ::unique_identifier_msgs::msg::dds_::UUID_ action_goal_id_;
               _sequence__seq sequence_;
         };

         typedef DDS_DCPSStruct_var < Fibonacci_Feedback_> Fibonacci_Feedback__var;
         typedef DDS_DCPSStruct_out < Fibonacci_Feedback_> Fibonacci_Feedback__out;
      }
   }
}




#endif
