//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: NestedMessage_Feedback_.h
//  Source: test_msgs\action\dds_opensplice\NestedMessage_Feedback_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _NESTEDMESSAGE_FEEDBACK__H_
#define _NESTEDMESSAGE_FEEDBACK__H_

#include "sacpp_mapping.h"
#include "Primitives_.h"
#include "Builtins_.h"
#include "Time_.h"
#include "UUID_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace action
   {
      namespace dds_
      {
         struct NestedMessage_Feedback_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Feedback_
         {
               ::unique_identifier_msgs::msg::dds_::UUID_ action_goal_id_;
               ::test_msgs::msg::dds_::Builtins_ nested_field_no_pkg_;
               ::test_msgs::msg::dds_::Primitives_ nested_field_;
               ::builtin_interfaces::msg::dds_::Time_ nested_different_pkg_;
         };

         typedef DDS_DCPSStruct_var < NestedMessage_Feedback_> NestedMessage_Feedback__var;
         typedef DDS_DCPSStruct_out < NestedMessage_Feedback_> NestedMessage_Feedback__out;
      }
   }
}




#endif
