//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: NestedMessage_Feedback_Dcps.h
//  Source: test_msgs\action\dds_opensplice\NestedMessage_Feedback_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _NESTEDMESSAGE_FEEDBACK_DCPS_H_
#define _NESTEDMESSAGE_FEEDBACK_DCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps.h"
#include "NestedMessage_Feedback_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace action
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Feedback_TypeSupportInterface;

         typedef NestedMessage_Feedback_TypeSupportInterface * NestedMessage_Feedback_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < NestedMessage_Feedback_TypeSupportInterface> NestedMessage_Feedback_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < NestedMessage_Feedback_TypeSupportInterface> NestedMessage_Feedback_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Feedback_DataWriter;

         typedef NestedMessage_Feedback_DataWriter * NestedMessage_Feedback_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < NestedMessage_Feedback_DataWriter> NestedMessage_Feedback_DataWriter_var;
         typedef DDS_DCPSInterface_out < NestedMessage_Feedback_DataWriter> NestedMessage_Feedback_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Feedback_DataReader;

         typedef NestedMessage_Feedback_DataReader * NestedMessage_Feedback_DataReader_ptr;
         typedef DDS_DCPSInterface_var < NestedMessage_Feedback_DataReader> NestedMessage_Feedback_DataReader_var;
         typedef DDS_DCPSInterface_out < NestedMessage_Feedback_DataReader> NestedMessage_Feedback_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Feedback_DataReaderView;

         typedef NestedMessage_Feedback_DataReaderView * NestedMessage_Feedback_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < NestedMessage_Feedback_DataReaderView> NestedMessage_Feedback_DataReaderView_var;
         typedef DDS_DCPSInterface_out < NestedMessage_Feedback_DataReaderView> NestedMessage_Feedback_DataReaderView_out;

         struct NestedMessage_Feedback_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < NestedMessage_Feedback_, struct NestedMessage_Feedback_Seq_uniq_> NestedMessage_Feedback_Seq;
         typedef DDS_DCPSSequence_var < NestedMessage_Feedback_Seq> NestedMessage_Feedback_Seq_var;
         typedef DDS_DCPSSequence_out < NestedMessage_Feedback_Seq> NestedMessage_Feedback_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Feedback_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef NestedMessage_Feedback_TypeSupportInterface_ptr _ptr_type;
            typedef NestedMessage_Feedback_TypeSupportInterface_var _var_type;

            static NestedMessage_Feedback_TypeSupportInterface_ptr _duplicate (NestedMessage_Feedback_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static NestedMessage_Feedback_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static NestedMessage_Feedback_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static NestedMessage_Feedback_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            NestedMessage_Feedback_TypeSupportInterface_ptr _this () { return this; }


         protected:
            NestedMessage_Feedback_TypeSupportInterface () {};
            ~NestedMessage_Feedback_TypeSupportInterface () {};
         private:
            NestedMessage_Feedback_TypeSupportInterface (const NestedMessage_Feedback_TypeSupportInterface &);
            NestedMessage_Feedback_TypeSupportInterface & operator = (const NestedMessage_Feedback_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Feedback_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef NestedMessage_Feedback_DataWriter_ptr _ptr_type;
            typedef NestedMessage_Feedback_DataWriter_var _var_type;

            static NestedMessage_Feedback_DataWriter_ptr _duplicate (NestedMessage_Feedback_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static NestedMessage_Feedback_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static NestedMessage_Feedback_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static NestedMessage_Feedback_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            NestedMessage_Feedback_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const NestedMessage_Feedback_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const NestedMessage_Feedback_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const NestedMessage_Feedback_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const NestedMessage_Feedback_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const NestedMessage_Feedback_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const NestedMessage_Feedback_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const NestedMessage_Feedback_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const NestedMessage_Feedback_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const NestedMessage_Feedback_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const NestedMessage_Feedback_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (NestedMessage_Feedback_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const NestedMessage_Feedback_& instance_data) = 0;

         protected:
            NestedMessage_Feedback_DataWriter () {};
            ~NestedMessage_Feedback_DataWriter () {};
         private:
            NestedMessage_Feedback_DataWriter (const NestedMessage_Feedback_DataWriter &);
            NestedMessage_Feedback_DataWriter & operator = (const NestedMessage_Feedback_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Feedback_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef NestedMessage_Feedback_DataReader_ptr _ptr_type;
            typedef NestedMessage_Feedback_DataReader_var _var_type;

            static NestedMessage_Feedback_DataReader_ptr _duplicate (NestedMessage_Feedback_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static NestedMessage_Feedback_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static NestedMessage_Feedback_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static NestedMessage_Feedback_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            NestedMessage_Feedback_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (NestedMessage_Feedback_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (NestedMessage_Feedback_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (NestedMessage_Feedback_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const NestedMessage_Feedback_& instance) = 0;

         protected:
            NestedMessage_Feedback_DataReader () {};
            ~NestedMessage_Feedback_DataReader () {};
         private:
            NestedMessage_Feedback_DataReader (const NestedMessage_Feedback_DataReader &);
            NestedMessage_Feedback_DataReader & operator = (const NestedMessage_Feedback_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Feedback_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef NestedMessage_Feedback_DataReaderView_ptr _ptr_type;
            typedef NestedMessage_Feedback_DataReaderView_var _var_type;

            static NestedMessage_Feedback_DataReaderView_ptr _duplicate (NestedMessage_Feedback_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static NestedMessage_Feedback_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static NestedMessage_Feedback_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static NestedMessage_Feedback_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            NestedMessage_Feedback_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (NestedMessage_Feedback_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (NestedMessage_Feedback_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (NestedMessage_Feedback_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (NestedMessage_Feedback_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const NestedMessage_Feedback_& instance) = 0;

         protected:
            NestedMessage_Feedback_DataReaderView () {};
            ~NestedMessage_Feedback_DataReaderView () {};
         private:
            NestedMessage_Feedback_DataReaderView (const NestedMessage_Feedback_DataReaderView &);
            NestedMessage_Feedback_DataReaderView & operator = (const NestedMessage_Feedback_DataReaderView &);
         };

      }
   }
}




#endif
