//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: NestedMessage_Goal_Response_.h
//  Source: test_msgs\action\dds_opensplice\NestedMessage_Goal_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _NESTEDMESSAGE_GOAL_RESPONSE__H_
#define _NESTEDMESSAGE_GOAL_RESPONSE__H_

#include "sacpp_mapping.h"
#include "Time_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace action
   {
      namespace dds_
      {
         struct NestedMessage_Goal_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs NestedMessage_Goal_Response_
         {
               DDS::Boolean accepted_;
               ::builtin_interfaces::msg::dds_::Time_ stamp_;
         };

         typedef DDS_DCPSStruct_var < NestedMessage_Goal_Response_> NestedMessage_Goal_Response__var;
         typedef NestedMessage_Goal_Response_&NestedMessage_Goal_Response__out;
      }
   }
}




#endif
