//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_Fibonacci_Goal_Response_.h
//  Source: test_msgs\action\dds_opensplice\Sample_Fibonacci_Goal_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _SAMPLE_FIBONACCI_GOAL_RESPONSE__H_
#define _SAMPLE_FIBONACCI_GOAL_RESPONSE__H_

#include "sacpp_mapping.h"
#include "Fibonacci_Goal_Response_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace action
   {
      namespace dds_
      {
         struct Sample_Fibonacci_Goal_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs Sample_Fibonacci_Goal_Response_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               Fibonacci_Goal_Response_ response_;
         };

         typedef DDS_DCPSStruct_var < Sample_Fibonacci_Goal_Response_> Sample_Fibonacci_Goal_Response__var;
         typedef Sample_Fibonacci_Goal_Response_&Sample_Fibonacci_Goal_Response__out;
      }
   }
}




#endif
