//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_NestedMessage_Goal_Request_.h
//  Source: test_msgs\action\dds_opensplice\Sample_NestedMessage_Goal_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _SAMPLE_NESTEDMESSAGE_GOAL_REQUEST__H_
#define _SAMPLE_NESTEDMESSAGE_GOAL_REQUEST__H_

#include "sacpp_mapping.h"
#include "NestedMessage_Goal_Request_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace action
   {
      namespace dds_
      {
         struct Sample_NestedMessage_Goal_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs Sample_NestedMessage_Goal_Request_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               NestedMessage_Goal_Request_ request_;
         };

         typedef DDS_DCPSStruct_var < Sample_NestedMessage_Goal_Request_> Sample_NestedMessage_Goal_Request__var;
         typedef DDS_DCPSStruct_out < Sample_NestedMessage_Goal_Request_> Sample_NestedMessage_Goal_Request__out;
      }
   }
}




#endif
