//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: CancelGoal_Request_.h
//  Source: action_msgs\srv\dds_opensplice\CancelGoal_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _CANCELGOAL_REQUEST__H_
#define _CANCELGOAL_REQUEST__H_

#include "sacpp_mapping.h"
#include "GoalInfo_.h"
#include "action_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace action_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct CancelGoal_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_action_msgs CancelGoal_Request_
         {
               ::action_msgs::msg::dds_::GoalInfo_ goal_info_;
         };

         typedef DDS_DCPSStruct_var < CancelGoal_Request_> CancelGoal_Request__var;
         typedef CancelGoal_Request_&CancelGoal_Request__out;
      }
   }
}




#endif
