//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: CancelGoal_Response_.h
//  Source: action_msgs\srv\dds_opensplice\CancelGoal_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _CANCELGOAL_RESPONSE__H_
#define _CANCELGOAL_RESPONSE__H_

#include "sacpp_mapping.h"
#include "GoalInfo_.h"
#include "action_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace action_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct CancelGoal_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_action_msgs CancelGoal_Response_
         {
               struct _goals_canceling__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < ::action_msgs::msg::dds_::GoalInfo_, struct _goals_canceling__seq_uniq_> _goals_canceling__seq;
               typedef DDS_DCPSSequence_var < _goals_canceling__seq> _goals_canceling__seq_var;
               typedef DDS_DCPSSequence_out < _goals_canceling__seq> _goals_canceling__seq_out;
               _goals_canceling__seq goals_canceling_;
         };

         typedef DDS_DCPSStruct_var < CancelGoal_Response_> CancelGoal_Response__var;
         typedef DDS_DCPSStruct_out < CancelGoal_Response_> CancelGoal_Response__out;
      }
   }
}




#endif
