//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_CancelGoal_Request_.h
//  Source: action_msgs\srv\dds_opensplice\Sample_CancelGoal_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _SAMPLE_CANCELGOAL_REQUEST__H_
#define _SAMPLE_CANCELGOAL_REQUEST__H_

#include "sacpp_mapping.h"
#include "CancelGoal_Request_.h"
#include "action_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace action_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct Sample_CancelGoal_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_action_msgs Sample_CancelGoal_Request_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               CancelGoal_Request_ request_;
         };

         typedef DDS_DCPSStruct_var < Sample_CancelGoal_Request_> Sample_CancelGoal_Request__var;
         typedef Sample_CancelGoal_Request_&Sample_CancelGoal_Request__out;
      }
   }
}




#endif
