//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_CancelGoal_Response_.h
//  Source: action_msgs\srv\dds_opensplice\Sample_CancelGoal_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _SAMPLE_CANCELGOAL_RESPONSE__H_
#define _SAMPLE_CANCELGOAL_RESPONSE__H_

#include "sacpp_mapping.h"
#include "CancelGoal_Response_.h"
#include "action_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace action_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct Sample_CancelGoal_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_action_msgs Sample_CancelGoal_Response_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               CancelGoal_Response_ response_;
         };

         typedef DDS_DCPSStruct_var < Sample_CancelGoal_Response_> Sample_CancelGoal_Response__var;
         typedef DDS_DCPSStruct_out < Sample_CancelGoal_Response_> Sample_CancelGoal_Response__out;
      }
   }
}




#endif
