//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_Fibonacci_Goal_Request_.h
//  Source: example_interfaces\action\dds_opensplice\Sample_Fibonacci_Goal_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _SAMPLE_FIBONACCI_GOAL_REQUEST__H_
#define _SAMPLE_FIBONACCI_GOAL_REQUEST__H_

#include "sacpp_mapping.h"
#include "Fibonacci_Goal_Request_.h"
#include "example_interfaces/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace example_interfaces
{
   namespace action
   {
      namespace dds_
      {
         struct Sample_Fibonacci_Goal_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_example_interfaces Sample_Fibonacci_Goal_Request_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               Fibonacci_Goal_Request_ request_;
         };

         typedef DDS_DCPSStruct_var < Sample_Fibonacci_Goal_Request_> Sample_Fibonacci_Goal_Request__var;
         typedef Sample_Fibonacci_Goal_Request_&Sample_Fibonacci_Goal_Request__out;
      }
   }
}




#endif
