//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetAvailableStates_Request_.h
//  Source: lifecycle_msgs\srv\dds_opensplice\GetAvailableStates_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _GETAVAILABLESTATES_REQUEST__H_
#define _GETAVAILABLESTATES_REQUEST__H_

#include "sacpp_mapping.h"
#include "lifecycle_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace lifecycle_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct GetAvailableStates_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableStates_Request_
         {
               DDS::Boolean dummy;
         };

         typedef DDS_DCPSStruct_var < GetAvailableStates_Request_> GetAvailableStates_Request__var;
         typedef GetAvailableStates_Request_&GetAvailableStates_Request__out;
      }
   }
}




#endif
