//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Log_.h
//  Source: rcl_interfaces\msg\dds_opensplice\Log_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _LOG__H_
#define _LOG__H_

#include "sacpp_mapping.h"
#include "Time_.h"
#include "rcl_interfaces/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace rcl_interfaces
{
   namespace msg
   {
      namespace dds_
      {
         struct Log_;
         const DDS::Octet Log__DEBUG = (DDS::Octet) 10;
         const DDS::Octet Log__INFO = (DDS::Octet) 20;
         const DDS::Octet Log__WARN = (DDS::Octet) 30;
         const DDS::Octet Log__ERROR = (DDS::Octet) 40;
         const DDS::Octet Log__FATAL = (DDS::Octet) 50;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_rcl_interfaces Log_
         {
               ::builtin_interfaces::msg::dds_::Time_ stamp_;
               DDS::Octet level_;
               DDS::String_mgr name_;
               DDS::String_mgr msg_;
               DDS::String_mgr file_;
               DDS::String_mgr function_;
               DDS::ULong line_;
         };

         typedef DDS_DCPSStruct_var < Log_> Log__var;
         typedef DDS_DCPSStruct_out < Log_> Log__out;
      }
   }
}




#endif
