//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GoalInfo_.h
//  Source: action_msgs\msg\dds_opensplice\GoalInfo_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _GOALINFO__H_
#define _GOALINFO__H_

#include "sacpp_mapping.h"
#include "Time_.h"
#include "UUID_.h"
#include "action_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace action_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct GoalInfo_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_action_msgs GoalInfo_
         {
               ::unique_identifier_msgs::msg::dds_::UUID_ goal_id_;
               ::builtin_interfaces::msg::dds_::Time_ stamp_;
         };

         typedef DDS_DCPSStruct_var < GoalInfo_> GoalInfo__var;
         typedef GoalInfo_&GoalInfo__out;
      }
   }
}




#endif
