//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GoalStatusArray_.h
//  Source: action_msgs\msg\dds_opensplice\GoalStatusArray_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _GOALSTATUSARRAY__H_
#define _GOALSTATUSARRAY__H_

#include "sacpp_mapping.h"
#include "GoalStatus_.h"
#include "action_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace action_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct GoalStatusArray_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_action_msgs GoalStatusArray_
         {
               struct _status_list__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < GoalStatus_, struct _status_list__seq_uniq_> _status_list__seq;
               typedef DDS_DCPSSequence_var < _status_list__seq> _status_list__seq_var;
               typedef DDS_DCPSSequence_out < _status_list__seq> _status_list__seq_out;
               _status_list__seq status_list_;
         };

         typedef DDS_DCPSStruct_var < GoalStatusArray_> GoalStatusArray__var;
         typedef DDS_DCPSStruct_out < GoalStatusArray_> GoalStatusArray__out;
      }
   }
}




#endif
