//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GoalStatus_.h
//  Source: action_msgs\msg\dds_opensplice\GoalStatus_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _GOALSTATUS__H_
#define _GOALSTATUS__H_

#include "sacpp_mapping.h"
#include "GoalInfo_.h"
#include "action_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace action_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct GoalStatus_;
         const DDS::Octet GoalStatus__STATUS_UNKNOWN = (DDS::Octet) 0;
         const DDS::Octet GoalStatus__STATUS_ACCEPTED = (DDS::Octet) 1;
         const DDS::Octet GoalStatus__STATUS_EXECUTING = (DDS::Octet) 2;
         const DDS::Octet GoalStatus__STATUS_CANCELING = (DDS::Octet) 3;
         const DDS::Octet GoalStatus__STATUS_SUCCEEDED = (DDS::Octet) 4;
         const DDS::Octet GoalStatus__STATUS_CANCELED = (DDS::Octet) 5;
         const DDS::Octet GoalStatus__STATUS_ABORTED = (DDS::Octet) 6;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_action_msgs GoalStatus_
         {
               GoalInfo_ goal_info_;
               DDS::Octet status_;
         };

         typedef DDS_DCPSStruct_var < GoalStatus_> GoalStatus__var;
         typedef GoalStatus_&GoalStatus__out;
      }
   }
}




#endif
